Update user identity service
Wealize/alastria-identity-lib-py pull request #1
Opened 2020-11-18 12:44 UTC by DrankoLQ

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix

## Description
This PR updates the UserIdentityService so it's able to sign transactions and get user nonce. It also updates some dependencies and some types

2020-11-19 17:22 UTC, javaguirre requested changes

2020-11-19 17:22 UTC, javaguirre commented on alastria_identity/services/identity.py
> +        transaction.gasPrice = 0
en python las variables son snake_case, pero a lo mejor esto viene de algun sitio que no podemos ponerlo a lo snake_case?

2020-11-19 17:23 UTC, DrankoLQ commented on alastria_identity/services/identity.py
> +        transaction.gasPrice = 0
Exacto, es como se llama en `web3`

2020-11-26 08:41 UTC, javaguirre approved these changes
yeeee haaa! 💯

2020-11-26 08:47 UTC, merged