creating presentation registry service
Wealize/alastria-identity-lib-py pull request #10
Opened 2021-01-07 15:41 UTC by danitico

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix

## Description

2021-01-08 10:42 UTC, anthares101 approved these changes
Nice! :+1:

2021-01-11 11:12 UTC, javaguirre requested changes

2021-01-11 11:12 UTC, javaguirre commented on alastria_identity/services/presentation_registry.py
> +    def add_subject_presentation(self, subject_presentation_hash: str, uri: str) -> Transaction:
Estos metodos son necesarios? No se pueden sacar de la informacion de la config de web3 del smart contract de alastria?

2021-01-11 21:30 UTC, victoriatnp commented on alastria_identity/services/presentation_registry.py
> +    def add_subject_presentation(self, subject_presentation_hash: str, uri: str) -> Transaction:
En el servicio de CredentialRegistryService también existe ese método, si no lo entendí mal, el subject sería el paciente/ usuario y eso no lo tenemos no?

2021-01-11 21:30 UTC, victoriatnp approved these changes

2021-01-12 09:12 UTC, danitico commented on alastria_identity/services/presentation_registry.py
> +    def add_subject_presentation(self, subject_presentation_hash: str, uri: str) -> Transaction:
Entiendo que así está bien

2021-01-12 09:14 UTC, javaguirre approved these changes

2021-01-12 09:14 UTC, javaguirre commented on alastria_identity/services/presentation_registry.py
> +    def add_subject_presentation(self, subject_presentation_hash: str, uri: str) -> Transaction:
no iba por ahi la cosa, pero vamos a aceptar el PR.

2021-01-12 09:14 UTC, merged