Update TokenService with missing methods
Wealize/alastria-identity-lib-py pull request #2
Opened 2020-11-26 17:20 UTC by DrankoLQ

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix

## Description
This PR updates the TokenService with new methods to generate missing tokens

2020-11-30 09:11 UTC, javaguirre requested changes

2020-11-30 09:11 UTC, javaguirre commented on alastria_identity/services/tokens.py
> +    def create_alastria_token(self,
Los parametros deberian ser un dataclass IMHO.

2020-11-30 09:11 UTC, javaguirre commented on alastria_identity/services/tokens.py
> +        if kid:
En el dataclass se podria uysar del tipo:

```python
header.update(mydataclass.get_header_update_values())
```

El metodo `get_header_update_values` devolveria un diccionario, vacio si no actualiza nada. El nombre del metodo lo he pensado en segundos, ponedle otro.

2020-11-30 09:11 UTC, javaguirre commented on alastria_identity/services/tokens.py
> +            self,
Idem arriba.

2020-11-30 09:11 UTC, javaguirre commented on alastria_identity/services/tokens.py
> +        if kid:
Idem arriba.

2020-12-01 08:50 UTC, DrankoLQ commented
No me fijé que ya había `dataclasses` para algunos de los tokens @javaguirre . Échale un ojo a estos cambios y vemos qué tal quedan 😬

2020-12-01 12:35 UTC, javaguirre requested changes

2020-12-01 12:35 UTC, javaguirre commented on alastria_identity/types/alastria_identity_creation.py
> +        if self.kid:
Esto no lo hemos hecho como comente, tener un dict que le pasemos al header update con los parametros que cambian, en vez de muchos ifs.

header.update (**get_parameters_to_be_updated())

2020-12-01 13:18 UTC, DrankoLQ commented on alastria_identity/types/alastria_identity_creation.py
> +        if self.kid:
Hmm la parte que me falta ver es cómo quitarnos tantos if para ver que el valor opcional se ha metido y no es None

2020-12-01 14:38 UTC, DrankoLQ commented on alastria_identity/types/alastria_identity_creation.py
> +        if self.kid:
Se me ocurre algo como

```python
        ...
        header.update(**self.get_optional_header_params())
        payload.update(**self.get_optional_payload_params())

        return {'header': header, 'payload': payload}

    def get_optional_header_params(self) -> dict:
        params = {}
        params.update(kid=self.kid) if self.kid else None
        params.update(jwk=self.jwk) if self.jwk else None
        return params

    def get_optional_payload_params(self) -> dict:
        params = {}
        params.update(jti=self.jti) if self.jti else None
        params.update(jti=self.exp) if self.exp else None
        params.update(jti=self.nbf) if self.nbf else None
        return params
```

2020-12-04 13:14 UTC, Miangame approved these changes
Good job!

2020-12-09 09:55 UTC, romerox3 approved these changes

2020-12-14 09:15 UTC, merged