Add Credential Registry service
Wealize/alastria-identity-lib-py pull request #4
Opened 2020-12-15 17:09 UTC by DrankoLQ

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix

## Description
This PR adds the Credential Registry service, used to interact with the `AlastriaCredentialRegistry` smart contract

2020-12-15 17:15 UTC, romerox3 approved these changes
Muy rico y claro! Esos test tienen muy buena pinta!

2020-12-15 17:15 UTC, romerox3 commented on alastria_identity/services/credential_registry.py
> +    def delegated(self, delegated_data):
Ya en modo monóculo 🧐  jajajaj aquí se te ha faltado el typing

2020-12-15 17:18 UTC, DrankoLQ commented on alastria_identity/services/credential_registry.py
> +    def delegated(self, delegated_data):
Touché! añadido 😬

2020-12-16 09:49 UTC, javaguirre requested changes

2020-12-16 09:49 UTC, javaguirre commented on alastria_identity/services/credential_registry.py
> +        data = self.delegated(ContractsService.AlastriaCredentialRegistry(self.endpoint).encodeABI(
Esto es una inyeccion de dependencias:

```python
def __init__(self, credential_registry, endpoint):
  self.credential... = ContractsService.AlastriaCredentialRegistry(endpoint)

...

def mimetodo(...):
  data = self.delegated(self.credential...).encodeABI

```

No entiendo bien por que el endpoint va en el constructor, pero si lo necesitamos en todas partes tendra sentido.

2020-12-16 09:49 UTC, javaguirre commented on alastria_identity/services/credential_registry.py
> +        return Transaction(
Esto es casi siempre igual, no podemos ser mas DRY y hacer un wrapper en un metodo y pasar solo el data? Esto es feo.

2020-12-16 09:49 UTC, javaguirre commented on alastria_identity/services/credential_registry.py
> +            args=[subject_credential_hash, uri]
Ahora veo que unicamente lo que van cambiando son los args, hay mucho codigo duplicado... para mi que esto hay que repensarlo, estamos metiendo mucha deuda tecnica IMHO.

2020-12-16 14:30 UTC, DrankoLQ commented on alastria_identity/services/credential_registry.py
> +        data = self.delegated(ContractsService.AlastriaCredentialRegistry(self.endpoint).encodeABI(
Por ponerte en contexto actualmente, ContractService tiene una serie de métodos estáticos que te permiten interactuar con los distintos smart contracts de Alastria (`AlastriaCredentialRegistry`) en este caso. El argumento que recibe, el endpoint, es la conexión de la aplicación con el nodo de la red para interactuar con esos smart contract. Podríamos cambiar ese argumento y pasarlo como argumento del constructor de la clase, pero pensé que era mejor hacerlo de esta forma con métodos estáticos. Por constructor sería tal que

```python
ContractsService(endpoint).AlastriaCredentialRegistry().encodeABI(...)
```

2020-12-16 14:32 UTC, DrankoLQ commented on alastria_identity/services/credential_registry.py
> +        return Transaction(
Yep, toda la razón. Por ahora estaba imitando la implentación de la biblioteca en TypeScript, pero es cierto que hay muchas partes repetitivas que podemos rehacerlas para simplificarlas. Voy a dedicarle un rato a ver qué se me ocurre 🙂

2020-12-16 15:10 UTC, DrankoLQ commented
Algunos cambios hechos, a ver qué tal lo ves @javaguirre cc @romerox3 🙂

2020-12-16 15:13 UTC, victoriatnp approved these changes
Yo lo veo mucho más limpio

2020-12-21 12:40 UTC, merged